"""Generate the synthetic offline dataset in ``fixtures/demo/``.

Every response here is invented: it mirrors the *structure* of each upstream (RSS,
article pages, westmetall tables, Sina JSONP, a resource-statement PDF) so that tests
and the offline demo exercise the real parsers, but no third-party text is copied.
Headlines are prefixed with "[示例]" and article links point at example.com.

The resource table in the PDF reuses the published Pilgangoora 2025 figures (facts,
not prose) so the extractor's ground truth can be checked offline.

Usage (dev dependencies required for reportlab):
    uv run python scripts/make_demo_fixtures.py
"""

import io
import json
import random
import shutil
from datetime import UTC, date, datetime, timedelta
from email.utils import format_datetime
from html import escape
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from mining_brief.agent.catalog import PROJECTS
from mining_brief.common.http import DiskStore, cache_key
from mining_brief.servers.news.sources import GOOGLE_NEWS, MINING_FRONT, search_feed_urls
from mining_brief.servers.price.sources import Commodity, source_for

ROOT = Path(__file__).resolve().parents[1] / "fixtures" / "demo"
SNAPSHOT = datetime(2026, 10, 8, 10, 0, tzinfo=UTC)
NEWS_QUERY = PROJECTS[0].news_query  # "PLS lithium"
DEMO_SITE = "https://example.com/mining-brief-demo"


def trading_days(start: date, end: date) -> list[date]:
    days, d = [], start
    while d <= end:
        if d.weekday() < 5:
            days.append(d)
        d += timedelta(days=1)
    return days


# --- prices ------------------------------------------------------------------------

LME_BASE = {
    Commodity.COPPER: (9800.0, 0.011),
    Commodity.ZINC: (2650.0, 0.012),
    Commodity.NICKEL: (15600.0, 0.014),
    Commodity.ALUMINIUM: (2480.0, 0.009),
    Commodity.LEAD: (1980.0, 0.010),
    Commodity.TIN: (31500.0, 0.013),
}


def walk(rng: random.Random, start: float, vol: float, n: int, drift: float = 0.0) -> list[float]:
    values, v = [], start
    for _ in range(n):
        v *= 1 + drift + rng.gauss(0, vol)
        values.append(v)
    return values


def westmetall_page(name: str, days: list[date], prices: list[float]) -> bytes:
    rows = []
    for d, p in sorted(zip(days, prices, strict=True), reverse=True):
        three_month = p * 0.994
        stock = 200_000 + int(p) % 50_000
        rows.append(
            f"<tr>\n<td >{d.day:02d}. {d.strftime('%B %Y')}</td>\n<td >{p:,.2f}</td>\n"
            f'<td >{three_month:,.2f}</td>\n<td class="last">{stock:,}</td>\n</tr>'
        )
    head = (
        '<tr class="shaded"><th class="text">date</th>'
        f'<th class="text">LME {name} Cash-Settlement</th>'
        f'<th class="text">LME {name} 3-month</th><th class="text last">LME {name} stock</th></tr>'
    )
    body = "\n".join(rows)
    return (
        "<!DOCTYPE html><html><head><title>Synthetic demo data</title></head><body>"
        f"<h1>Market data</h1><h2>{name}</h2><!-- SYNTHETIC: generated by "
        f"scripts/make_demo_fixtures.py, not real prices -->\n<table >\n<thead>\n{head} "
        f"</thead>\n<tbody>\n{body}\n</tbody></table></body></html>"
    ).encode()


def sina_payload(days: list[date], prices: list[float]) -> bytes:
    records = []
    for d, p in zip(days, prices, strict=True):
        o, c = p * 0.998, p * 1.002
        records.append(
            {
                "d": d.isoformat(),
                "o": f"{o:.3f}",
                "h": f"{max(o, c) * 1.01:.3f}",
                "l": f"{min(o, c) * 0.99:.3f}",
                "c": f"{c:.3f}",
                "v": str(100000 + int(p) % 90000),
                "p": str(400000 + int(p) % 20000),
                "s": f"{round(p, -1):.3f}",
            }
        )
    return (
        "/*<script>location.href='//sina.com';</script>*/\n/* SYNTHETIC demo data */\n"
        f"var _LC0=({json.dumps(records, separators=(',', ':'))});"
    ).encode()


# --- news --------------------------------------------------------------------------

ARTICLE_BODY = (
    "This page is synthetic demo content generated for offline runs and tests of the "
    "mining brief agent. It imitates the layout of a mining news article so that the "
    "extraction pipeline has realistic structure to work with, but it does not report "
    "real events and must not be read as news. {topic} The paragraph continues with "
    "neutral filler about how analysts usually compare production guidance, resource "
    "estimates and benchmark prices when they review a {commodity} project, and how "
    "they record the source of every number they quote. A second paragraph explains "
    "that the offline dataset is regenerated by a script, so its contents are stable "
    "across test runs and contain no third-party text. A third paragraph exists only "
    "to give the article enough length for the extractor to treat it as the main body."
)


def slug(text: str) -> str:
    return "".join(ch if ch.isalnum() else "-" for ch in text.lower()).strip("-")[:60]


PROJECT_ITEMS = [
    ("PLS lithium operations update (sample)", 1),
    ("Pilgangoora expansion timeline explained (sample)", 2),
    ("PLS Group quarterly report preview (sample)", 4),
]
MARKET_ITEMS = [
    ("Lithium carbonate futures in focus (sample)", 1),
    ("Spodumene concentrate shipments overview (sample)", 2),
    ("Battery metals week in review (sample)", 3),
    ("Lithium project financing explainer (sample)", 5),
]
OTHER_TOPICS = [
    "Copper smelter maintenance schedule",
    "Gold miners and hedging programs",
    "Iron ore port inventories",
    "Nickel processing technology",
    "Zinc concentrate treatment charges",
    "Rare earths supply chain mapping",
    "Uranium enrichment capacity",
    "Cobalt artisanal mining standards",
    "Tin market liquidity",
    "Aluminium energy costs",
    "Mine closure planning",
    "Exploration drilling budgets",
    "Mining equipment electrification",
    "Tailings storage standards",
    "Critical minerals policy tracker",
    "Royalty regime comparisons",
    "Water use in mining",
    "Mine safety statistics",
]


def rss(title: str, items: list[dict[str, str]]) -> bytes:
    body = []
    for it in items:
        body.append(
            "<item>"
            f"<title>{escape(it['title'])}</title><link>{escape(it['link'])}</link>"
            f"<pubDate>{it['pubDate']}</pubDate>"
            f"<description>{escape(it.get('description', ''))}</description>"
            + (
                f"<content:encoded><![CDATA[{it['content']}]]></content:encoded>"
                if it.get("content")
                else ""
            )
            + (
                f'<source url="{escape(it["source_url"])}">{escape(it["source"])}</source>'
                if it.get("source")
                else ""
            )
            + "".join(f"<category>{escape(c)}</category>" for c in it.get("tags", []))
            + "</item>"
        )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">'
        f"<channel><title>{escape(title)}</title><link>{DEMO_SITE}</link>"
        "<description>SYNTHETIC demo feed</description>" + "".join(body) + "</channel></rss>"
    ).encode()


def mining_item(title: str, days_ago: int, commodity: str) -> tuple[dict[str, str], str, bytes]:
    url = f"{DEMO_SITE}/{slug(title)}/"
    lead = f"[示例] {title}: synthetic {commodity} story used by offline demos."
    text = ARTICLE_BODY.format(topic=lead, commodity=commodity)
    published = SNAPSHOT - timedelta(days=days_ago, hours=3)
    item = {
        "title": f"[示例] {title}",
        "link": url,
        "pubDate": format_datetime(published),
        "description": lead,
        "content": f"<p>{escape(text)}</p>",
        "tags": ["Battery Metals"] if commodity == "lithium" else ["Markets"],
    }
    page = (
        "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
        f"<title>[示例] {escape(title)}</title>"
        "<meta property='og:site_name' content='Mining Brief Demo'>"
        f"<meta property='og:title' content='[示例] {escape(title)}'>"
        f"<meta property='article:published_time' content='{published.isoformat()}'>"
        "</head><body><header>Mining Brief Demo (synthetic)</header><main><article>"
        f"<h1>[示例] {escape(title)}</h1>"
        + "".join(f"<p>{escape(p)}.</p>" for p in text.split(". ") if p)
        + "</article></main><footer>Synthetic content</footer></body></html>"
    ).encode()
    return item, url, page


def google_item(title: str, days_ago: int, n: int) -> dict[str, str]:
    published = SNAPSHOT - timedelta(days=days_ago, hours=1)
    return {
        "title": f"[示例] {title} - Demo Wire",
        "link": f"https://news.google.com/rss/articles/SYNTHETIC-{n}",
        "pubDate": format_datetime(published),
        "description": "",
        "source": "Demo Wire",
        "source_url": DEMO_SITE,
    }


# --- report PDF ----------------------------------------------------------------------

PDF_PAGES = [
    [
        "SYNTHETIC DEMO DOCUMENT - generated by scripts/make_demo_fixtures.py",
        "Not an ASX announcement. The resource table on page 2 reproduces the",
        "published Pilgangoora Mineral Resource figures (as at 31 March 2025, JORC Code",
        "2012) so the extractor can be tested offline; all prose here is synthetic.",
        "",
        "Pilgangoora Mineral Resource update (demo)",
        "The Mineral Resource is classified in accordance with the JORC Code 2012.",
    ],
    [
        "Mineral Resource update",
        "The reported Mineral Resource has been classified in accordance with the JORC",
        "Code, 2012 Edition (JORC). Reporting uses a cut-off of 0.2% Li2O.",
        "Table 1 - Pilgangoora Operation updated JORC Mineral Resource as at 31 March 2025 (using 0.2% Li2O",
        "cut off).",
        "Category",
        "Tonnes Li2O Ta2O5 Fe2O3 Li2O Ta2O5",
        "(Mt) (%) (ppm) (%) (Mt) (M lb)",
        "Measured 19 1.34 113 0.41 0.3 5",
        "In-situ Indicated 349 1.29 121 0.54 4.5 93",
        "(>=0.2% Li2O)",
        "Inferred 70 1.25 134 0.58 0.9 21",
        "Sub-Total 438 1.29 122 0.54 5.6 118",
        "Measured 1 1.10 106 0.75 0.0 0",
        "Stockpiles Indicated 7 0.93 82 3.39 0.1 1",
        "(>=0.2% Li2O)",
        "Inferred - - - - - -",
        "Sub-Total 8 0.95 85 3.03 0.1 2",
        "Measured 20 1.32 113 0.43 0.3 5",
        "Indicated 356 1.29 120 0.60 4.6 94",
        "Pilgangoora",
        "Inferred 70 1.25 134 0.58 0.9 21",
        "Total 446 1.28 122 0.59 5.7 120",
        "Note: rounding applied to numbers in Table above.",
    ],
    ["Appendix (synthetic): no further resource tables in this demo document."],
]


def resource_pdf() -> bytes:
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4, invariant=True)  # invariant: reproducible bytes
    pdf.setTitle("SYNTHETIC demo resource statement")
    for lines in PDF_PAGES:
        y = 800
        for line in lines:
            pdf.setFont("Helvetica", 9)
            pdf.drawString(40, y, line)
            y -= 14
        pdf.showPage()
    pdf.save()
    return buffer.getvalue()


# --- assembly ----------------------------------------------------------------------


def main() -> None:
    if ROOT.exists():
        shutil.rmtree(ROOT)
    store = DiskStore(ROOT / "http")
    manifest: dict[str, dict[str, object]] = {}

    def put(url: str, content: bytes, content_type: str) -> None:
        store.write(url, content, content_type, SNAPSHOT)
        manifest[cache_key(url)] = {
            "url": url,
            "recorded_at": SNAPSHOT.isoformat(),
            "synthetic": True,
        }

    rng = random.Random(20261008)  # noqa: S311 - reproducible demo data, not crypto
    lme_days = trading_days(date(2026, 1, 2), date(2026, 10, 7))
    for commodity, (base, vol) in LME_BASE.items():
        prices = walk(rng, base, vol, len(lme_days))
        put(
            source_for(commodity).url,
            westmetall_page(commodity.value.capitalize(), lme_days, prices),
            "text/html",
        )
    lc_days = trading_days(date(2023, 7, 21), date(2026, 10, 8))
    lc_prices = walk(rng, 220000.0, 0.012, len(lc_days), drift=-0.0006)
    put(
        source_for(Commodity.LITHIUM_CARBONATE).url,
        sina_payload(lc_days, lc_prices),
        "application/javascript",
    )

    project, market = [], []
    for title, age in PROJECT_ITEMS:
        item, url, page = mining_item(title, age, "lithium")
        project.append(item)
        put(url, page, "text/html; charset=utf-8")
    for title, age in MARKET_ITEMS:
        item, url, page = mining_item(title, age, "lithium")
        market.append(item)
        put(url, page, "text/html; charset=utf-8")
    others = [mining_item(t, 1 + i % 9, "general")[0] for i, t in enumerate(OTHER_TOPICS)]

    feeds = search_feed_urls(NEWS_QUERY, 7)
    search_url, commodity_url, front_url, google_url = feeds
    if front_url != MINING_FRONT or google_url != GOOGLE_NEWS.format(query="PLS%20lithium", days=7):
        raise RuntimeError("feed URL layout changed; update make_demo_fixtures.py")
    put(
        search_url,
        rss("You searched for PLS lithium - DEMO", project[:2] + market[:1]),
        "application/rss+xml",
    )
    put(commodity_url, rss("Lithium - DEMO", market + project[2:]), "application/rss+xml")
    put(front_url, rss("DEMO front page", others + market[:2]), "application/rss+xml")
    google = [
        google_item(t, a, i)
        for i, (t, a) in enumerate([*PROJECT_ITEMS, ("PLS Group investor day notes (sample)", 3)])
    ]
    put(google_url, rss('"PLS lithium" - Google News (DEMO)', google), "application/xml")

    put(PROJECTS[0].reports[0].url, resource_pdf(), "application/pdf")

    (ROOT / "MANIFEST.json").write_text(
        json.dumps(
            {
                "_comment": "SYNTHETIC offline dataset; regenerate with scripts/make_demo_fixtures.py",
                **dict(sorted(manifest.items())),
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        "utf-8",
        newline="\n",
    )
    print(f"wrote {len(manifest)} synthetic responses to {ROOT}")


if __name__ == "__main__":
    main()
