"""Record real upstream responses into the LOCAL cache.

Real responses are third-party content, so they are kept in ``MB_CACHE_DIR`` (gitignored)
and never committed; the repository ships synthetic data generated by
``scripts/make_demo_fixtures.py`` instead. After recording, ``--offline``
runs serve these snapshots from the cache.

Usage: uv run python scripts/record_fixtures.py [price|news|pdf ...]
"""

import asyncio
import sys
from collections.abc import Awaitable, Callable
from datetime import timedelta

from mining_brief.agent.catalog import PROJECTS
from mining_brief.common.config import get_settings
from mining_brief.common.http import CachedHttp, record_fixture
from mining_brief.servers.news.service import NewsService
from mining_brief.servers.news.sources import search_feed_urls
from mining_brief.servers.price.sources import Commodity, source_for

# Queries the demo brief issues; recording them makes the brief answerable offline.
DEMO_NEWS_QUERIES = [(p.news_query, 7) for p in PROJECTS]
ARTICLES_PER_QUERY = 8


async def price_targets(_: CachedHttp) -> list[str]:
    return [source_for(c).url for c in Commodity]


async def news_targets(http: CachedHttp) -> list[str]:
    """Search feeds for the demo queries plus the top full-text articles they return."""
    urls: list[str] = []
    service = NewsService(http)
    for query, days in DEMO_NEWS_QUERIES:
        urls += search_feed_urls(query, days)
        result = await service.search(query, days)
        urls += [i.url for i in result.items if i.full_text_available][:ARTICLES_PER_QUERY]
    return list(dict.fromkeys(urls))


async def pdf_targets(_: CachedHttp) -> list[str]:
    return [r.url for p in PROJECTS for r in p.reports]


TARGETS: dict[str, Callable[[CachedHttp], Awaitable[list[str]]]] = {
    "price": price_targets,
    "news": news_targets,
    "pdf": pdf_targets,
}


async def main(groups: list[str]) -> int:
    settings = get_settings().model_copy(update={"offline": False})
    http = CachedHttp(settings)
    failures = 0
    try:
        for group in groups or list(TARGETS):
            for url in await TARGETS[group](http):
                try:
                    result = await http.get(url, ttl=timedelta(0))
                    record_fixture(settings.cache_dir, result)
                    print(f"[ok]   {group:6} {len(result.content):>8} B  {url}")
                except Exception as exc:  # report every target, then fail at the end
                    failures += 1
                    print(f"[fail] {group:6} {url}: {exc}")
    finally:
        await http.aclose()
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main(sys.argv[1:])))
